name: CI Tests

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.6.0
      - uses: oven-sh/setup-bun@v2.0.2
      - uses: docker/setup-docker-action@v4

      - name: Pull PixelArch Container
        run: docker pull lunamidori5/pixelarch:emerald

      - name: Install Qt runtime dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libegl1

      - name: Sync
        run: uv sync --group ci

      - name: Tests
        run: uv run pytest -q --maxfail=1
